version: "3.9"
services:
  daphne:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 8000 AJHome.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - $PWD:/usr/src/app
    container_name: daphne_container
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis_container
    restart: always
